server:
  port: ${SERVER_PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/guessDatabase?useSSL=false&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}