server:
  port: ${SERVER_PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database : mysql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/guessDatabase?createDatbaseIfNotExist=true}
    username: ${spring_datasource_username:root}
    password: ${spring_datasource_password:local_db_pass}
    plateforme : mysql